### PR TITLE
Added search with params

### PR DESCRIPTION
**Pull request by miwand**
Just added the already created function searchWithParams to allow for customization of parameters fitting to specific needs.

### CODE REVIEW

**Comment by SSheldon** [comment]
Hey @miwand, what parameters do you need to customize that the this doesn't currently allow?

I've just noticed we're missing some, like `category_filter`, `deals_filter`, etc. Maybe adding parameters for these would be a friendlier way to solve the issue? I'd like to keep the interface strongly typed wherever possible so that users don't have to guess which types are expected :)

**Comment by miwand** [comment]
Hey @SSheldon, I wish I knew about this API before when I was using it. I was helping another individual with this API and he wanted to use it for category_filter and bounds. I noticed that the option was not there, so I just made it inside the client+search.h. Also I was using the pods in the swift and found that I had to manually add in all the header files into a bridging header. Great work on the framework.

**Comment by SSheldon** [comment]
Thanks for the extra details and kind words, @miwand :) And yep, definitely looks like there's no way to specify `category_filter`, I've ticketed that and the other missing items in #34.

I think it'd be preferable if we could add a `categoryFilter:(NSArray<NSString *> *)` parameter, mind if we take a crack at that before deciding to merge this? You're off course welcome to send a PR for that, no pressure though since we've still got some kinks to work out as this library was just published.

> Also I was using the pods in the swift and found that I had to manually add in all the header files into a bridging header.

Did you by chance have `use_frameworks!` in your podfile? If so, this pod should get compiled as a framework and you'll be able to `import YelpAPI` instead of adding it to your bridging header. Yelp/yelp-api#123 is an example where I tried that out :)

**Comment by SSheldon** [comment]
Hey @miwand, sorry for the delay! We've just published version 1.1.0 with a new `YLPQuery` object that'll allow more customization for searches (#37). Now, if you want to search using a category filter and bounds, you could do:
``` objc
YLPQuery *query = [[YLPQuery alloc] initWithBounds:bounds];
query.categoryFilter = @[@"bars", @"french"];
[client searchWithQuery:query completionHandler:...];
```

Hopefully that meets your use case :) I'm going to close out this PR then.

**Pull request closed without merging**
